replicaCount: 1

image:
  repository: ghcr.io/tianaiwu-gif/estrion-python-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

config:
  environmentName: ArgoCD-Test-Environment

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false

resources: {}
